[build]
  publish = "build" # your build output folder
  command = "npm run build" # or your build command

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-cache"
 